apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javapp
  template:
    metadata:
      labels:
        app: javapp
    spec:
      containers:
      - name: java-api
        image: rabee123/task2:1
        ports:
        - containerPort: 8080

